### PR TITLE
Adjust handling of FCP/DaVinci Resolve timeline XML file content

### PR DESCRIPTION
**Pull request by mrolappe**
This is related to issue #811 and fixes the import of the 'old style' FCP  XML files as exported from DaVinci resolve.

The code uses the clipitems' in and out attributes as source for start and end. It also adds existence checks regarding the XML element hierarchy.

### CODE REVIEW

**Comment by lublak** [comment]
can we merge it?

**Comment by mifi** [comment]
Now that it seems that the xml logic is getting more complex, it would be nice to be able to add a unit test actually for these two different kinds of files. (e.g. one unit test for [this file](https://github.com/mifi/lossless-cut-fixtures/blob/master/Final%20Cut%20Pro%20XMEML.xml) and one for the file you are using.) Or could you share an example file that was reproducing the problem that this PR fixes, then I can try to make a unit test?

**Comment by mifi** [comment]
I added a test now for the existing file

**Comment by mrolappe** [comment]
Let me know if you need anything else or if you can use some help.

**Comment by mifi** [comment]
Yes if you can provide a sample xml file that fails before this PR but works after this PR then i can add a test for it

**Comment by mrolappe** [comment]
Sure, please find attached a suitable timeline XML file (extension changed to make GitHub upload happy).

[Timeline 1.xml.txt](https://github.com/mifi/lossless-cut/files/7534455/Timeline.1.xml.txt)

**Comment by mifi** [comment]
Thanks for your file. However I tried this with the current version of losslesscut, and it does not produce any error, or am I misunderstanding something?

**Comment by mrolappe** [comment]
I had tested with the version I had installed back then (3.37.0) and get an error message.

Having just checked with the latest release 3.39.0 I get the same error:

llc_err

**Comment by mifi** [comment]
whoops my bad. i must have been on this pr when i tested! will update the test now

**Comment by mifi** [comment]
thanks!

**Pull request merged**
