### PR TITLE
Document that lossless transpose is also supported

### PR DESCRIPTION
**Pull request by quorten**
I really like that LosslessCut can transpose video segments, let's make sure this is documented right up in the list where potential new users can see it.

### CODE REVIEW

**Comment by mifi** [comment]
Hi. I'm not very familiar with the term "transposing". When I google transposing video I get results for changing pitch/speed of video, is this what you mean? If so, I'm not sure how you do that with LosslessCut

**Comment by Shakil-Shahadat** [comment]
I think ['transpose'](https://www.goodwordguide.com/define/transpose) here means `to change the order or arrangement of`.

**Comment by mifi** [comment]
Ok, is "transposing" a common terminology for Non linear video editing? If so then I'm open to adding that

**Comment by Shakil-Shahadat** [comment]
I don't know, not a native English speaker, neither a video editor. 'Rearrange' could be a better term here.

**Comment by quorten** [comment]
I think you're right that "transpose" is ambiguous/confusing in this context, I was also thinking "rearrange" would be more clear.  I'll update.

**Pull request merged**
