### PR TITLE
Minor font/language fixes

### PR DESCRIPTION
**Pull request by VladWinner**
* fix language names in lower case
* use proper font stack
* changed to Open Sans SC

### CODE REVIEW

**Comment by mifi** [comment]
why is Noto Sans needed? (which OS/browser has that?)

**Comment by VladWinner** [comment]
1. Noto Sans is minimally different from embedded Open Sans
2. (if Noto Sans is pre-installed on PC) Its inclusion in font stack will help to better display text (more consistency) in non-Latin languages; non-Latin glyphs are not included in src/fonts/*.woff2 files
Before:
image
After:
image

> which OS/browser has that?

Chrome/Chromium OS (Chromebook), Android, some Linux distros

**Comment by mifi** [comment]
wouldn't it be better to include Noto Sans inside src/fonts so that everyone can take advantage of it?

**Comment by VladWinner** [comment]
@mifi 
Good idea! I just converted the latest version of Noto Sans to WOFF2, also applied `salt` OT feature to make it more similar to the previous font (Open Sans) and used Semi Condensed style to minimize cases when the text doesn't fit in one line in some languages and make it more suitable as UI font. 
About the font stack: I have added OG 'Noto Sans' to the font stack list as a workaround in case more glyphs are needed in the future.
I hope you like the change :3

**Comment by mifi** [comment]
very nice! font noob here got a few questions:

1. Does semicondensed affect latin text too?
2. What does "applied `salt`" mean?
3. Could you provide some instructions for
  - where you found the fonts
  - how you did the conversion from ttf to woff2
  - how to apply the "salt"?
  in case we need to re-do this process in the future for new versions of the font...

**Comment by VladWinner** [comment]
> Does semicondensed affect latin text too?

Yes, affects all letters.

> What does "applied salt" mean?

This means that I have forcibly enabled 'salt' OpenType feature (by default). 'salt' = '[Stylistic Alternates](https://helpx.adobe.com/fonts/using/open-type-syntax.html#salt)'

ezgif com-gif-maker (1)

Alternative glyphs are used by Google when compiling 'Open Sans' font family from 'Noto Sans' sources:
image

> where you found the fonts

I used NotoSans-SemiCondensed*.ttf fonts from this directory:
https://github.com/notofonts/notofonts.github.io/tree/main/fonts/NotoSans/unhinted/ttf

> how you did the conversion from ttf to woff2

I used [woff2 utility](https://github.com/google/woff2), `woff2_compress` command (see ['Run' instructions](https://github.com/google/woff2#run))

> how to apply the "salt"?

Personally, I used [OTFeatureFreezer](https://github.com/twardoch/fonttools-opentype-feature-freezer) to “freeze” (show by default using glyph substitution) these glyphs into a font family. This was done before TTF→WOFF2 conversion.
Alternatively, you could skip this step for future updates and use an additional line in src/main.css:
```
html {
  font-family: 'Noto Sans SemiCondensed', 'Noto Sans', sans-serif;
  font-size: 16px;
  font-feature-settings: "salt"; /* this one */
}
```
But I didn't use this CSS method because I'm not sure what the fallback font (`sans-serif`) will look like on different systems with 'salt' on.

> also why is NotoSans 10x the kb size of OpenSans?

Because it includes more glyphs (3872 vs 231 glyphs in open-sans-v17-latin*.woff2) than just the Latin alphabet. However, I didn't add [CJK characters](https://en.wikipedia.org/wiki/CJK_characters) manually, so as not to increase the build size even more.

ezgif com-gif-maker (2)

> Is it because opensans only supports latin?

In fact, Open Sans font family supports more glyphs than just the Latin alphabet (~1140 glyphs), but in the current build of LosslessCut, "lightweight" WOFF2 files with a limited set of characters are used, which is why some supported languages are reset to the system font, even if Open Sans initially supports them.

As a good compromise with the build size, I can suggest just using [Open Sans SemiCondensed](https://fonts.google.com/download?family=Open%20Sans), which doesn't contain some specific glyphs, but still extends language support (+Cyrillic, Greek etc.). However, Noto Sans font family supports even more languages, including CJK, so it makes sense to specify it in the font stack anyway to guarantee better text display.

**Comment by mifi** [comment]
I did try out your branch now. Personally I find it a bit unnatural looking (squished) with latin, see screenshot:

Screenshot 2023-02-16 at 23 56 38

is there any way to make latin look "normal" but cyrillic semicondensed? 

Anyways I took the liberty of updating your PR and instead of manually including opensans, I use `yarn install @fontsource/open-sans` https://fontsource.org/docs/getting-started

then I just imported everything. that should include all character sets:
```
import '@fontsource/open-sans/300.css';
import '@fontsource/open-sans/300-italic.css';
import '@fontsource/open-sans/400.css';
import '@fontsource/open-sans/400-italic.css';
import '@fontsource/open-sans/500.css';
import '@fontsource/open-sans/500-italic.css';
import '@fontsource/open-sans/600.css';
import '@fontsource/open-sans/600-italic.css';
import '@fontsource/open-sans/700.css';
import '@fontsource/open-sans/700-italic.css';
import '@fontsource/open-sans/800.css';
import '@fontsource/open-sans/800-italic.css';
```

What do you think?

**Comment by VladWinner** [comment]
> https://fontsource.org/docs/getting-started

I like it.

> unnatural looking (squished)

I think it's a matter of habit.

> What do you think?

…How about using **Fira Sans** with 'tnum' (Tabular Figures) on? 
https://fontsource.org/fonts/fira-sans

image

**Comment by mifi** [comment]
btw could an alternative be to set css `letter-spacing` to a low value if language is set to Russian?

**Comment by VladWinner** [comment]
> letter-spacing

Actually, I haven't even tried it yet.

> How about using Fira Sans with 'tnum' (Tabular Figures) on?

If you don't like Fira Sans, we can just merge PR in the current state.

**Comment by mifi** [comment]
I tried fira sans and it also looks a bit odd, I think also because the whole LosslessCut UI was now designed around open sans, and because fira sans is narrower, there is a lot of empty horizontal space around text. So I'm gonna merge this PR for now, but we can revisit this later if needed. Thanks alot!

PS: let me know if you can find some `letter-spacing` value that works well for Russian, and I can apply it to the `ru` locale in losslesscut!

**Pull request merged**
