### PR TITLE
Add desktop and appdata files for downstreams

### PR DESCRIPTION
**Pull request by muelli**
This intends to make the lives of downstreams a bit easier. That is, not every downstream needs to create and maintain those files.
I would hope that electron-builder can generate those, but I have absolutely no idea how to make it behave accordingly.

I intend to make a [flatpak](https://github.com/muelli/flathub/tree/cutloss) and publish it on flathub. Having the desktop and the appdata files upstream helps. Also, would you be interested in co-maintaining the app on flathub?

### CODE REVIEW

**Comment by mifi** [comment]
Thanks for your PR. Why is one file inside src and the other outside? Are they both supposed to be part of the application bundle?

**Comment by muelli** [comment]
No good reason, I think.
The .desktop file is certainly landing on the user's system after installation. The appdata file might be consumed before, e.g. by software catalogues. I think my mental model made me put the appdata file outside the src directory. But in the end it doesn't matter.

**Comment by mifi** [comment]
So what you need is just these two files to be hosted somewhere here in the github repo? They don't need to be part of the built binary, correct? if that's the case then i suggest moving the other file also to root. because it is not part of the built source

**Comment by muelli** [comment]
well. no. They should be part of the release, i.e. in the released tarballs. And normal apps do install those files to the user's machine, e.g. through a make install. Even better if the files are being maintained. That affects primarily the appdata file with the release information. The desktop file doesn't change much, I reckon. (Ah, I have just remembered a reason why the desktop file lives in `src`: The executable path needs to be adapted to the prefix where the app is being installed.)

**Comment by mifi** [comment]
Ok, but I don' think that these files will be included automatically in the release files just by adding them.
The build is only configured to include certain files like `build/**` and `node_modules`
We are currently distributing three different linux binaries: appimage, snap and tar.bz2. I don't understand why `appdata.xml` and `.desktop` files need to be inside of those binaries

**Comment by muelli** [comment]
This is how GNU/Linux distributions work. They use these files to offer a, say, icon for the user to click on. And to show them information about the software in a software catalogue, e.g. GNOME Software.  The standards are maintained [here](https://people.freedesktop.org/~hughsient/appdata/) and [here](https://www.freedesktop.org/wiki/Specifications/desktop-entry-spec/).

I've just picked a random Ubuntu package, Pitivi, and [you can see](https://packages.ubuntu.com/bionic/amd64/pitivi/filelist) that it ships those files. KDE's equivalent does the same: [desktop file](https://packages.ubuntu.com/focal/amd64/kdenlive/filelist), [appdata file](https://packages.ubuntu.com/focal/all/kdenlive-data/filelist).

I hope I could shed some light into why downstreams make use of those files. As I have absolutely no clue about Electron, I don't know how to have those files included in the tarball. While it would be nice to have them in the release, I bet downstreams are smart enough to take the file out of the git tree, if necessary. That's still better than crafting and maintaining these files on every downstream end.

**Comment by mifi** [comment]
Ok I see. I'm happy to include them in the repository as a first step if that sounds good? if so please move the one that's in src/ to the root and i can merge

**Comment by muelli** [comment]
cool! Thanks :)

**Pull request merged**
