### PR TITLE
Makes end time the end of the video by default

### PR DESCRIPTION
**Pull request by r3dcrosse**

### CODE REVIEW

**Comment by r3dcrosse** [comment]
Travis CI fails check because it wasn't able to install Node version 4 or 6.
Travis CI error

**Comment by mifi** [comment]
Hi and thanks for the PR!

The issue you had was a temporary issue with travis or nodejs.org (it failed to download node.js). I retriggered build and it's working now.

I think your idea is good, but I'm a little hesitant on depending too much on the response from ffprobe. It might not work correctly on all formats etc. I feel it is safer (and simpler) to use the duration returned from the html5 video element. I made a branch with a commit. Do you agree?
https://github.com/mifi/lossless-cut/commit/664878f5919466e675a359091c41e5be7705b803

**Comment by r3dcrosse** [comment]
I haven't tested ffprobe with different formats so I wasn't sure how reliable it would be. I agree that getting the duration returned from the html5 video element would be much simpler!

Thanks for taking a look at it!

**Comment by mifi** [comment]
I have now merged my branch from 664878f5919466e675a359091c41e5be7705b803. Closing this.

**Pull request closed without merging**
