### PR TITLE
move from zip/exe to 7zip only

### PR DESCRIPTION
**Pull request by mifi**
https://github.com/mifi/lossless-cut/issues/1072#issuecomment-1066026323

### CODE REVIEW

**Comment by Droyk** [comment]
after much thinking, I think the only big downside for me is it extracts its files every time the user opens up the application which causes a delay in opening the said application. if `.exe` would just extract all files in the same directory & won't delete them after using the application. then I think it is way better to go with `.exe`. it's much easier than a `.zip` or `.7zip` file. 

the convince of `.exe` is that first it is self-extracting and the 2nd the self-extraction process is overs it opens the application. & third, it is better compressed than a `.zip` file!

`.zip` requires the user to first extract the said application and then open it. a bit inconvenient but since it beats the slight delay of extracting it through `.exe` every time the user opens the application. makes it well worth it. the same thing also applies to `.7zip` but requires an extra step of installing the 7zip application first. the advantages are better compression ratio and bandwidth savings.

I think if the problem with `.exe` can be handled then it would be better to go with `.exe` & `.7zip` but if it can't then yeah why not?

**Comment by mifi** [comment]
Correct me if I'm wrong but I think .exe will not delete the files in the TMP folder after closing the app (or can you confirm that it does?)
But I think what's happening is that the Windows operating system will delete the temp files in certain circumstances, like when rebooting. Thus needing to extract again..

**Comment by Droyk** [comment]
every damn time! at least on my system!

https://user-images.githubusercontent.com/15848350/158052991-b012993a-1ebb-4534-aa7f-3f6611c6d5b0.mp4

apologies for the jarring quality used smart-cut!

**Comment by Droyk** [comment]
seems to be rebuilding itself from the ground up every damn time!

here is the screencap

https://user-images.githubusercontent.com/15848350/158053965-289afdff-73e5-48fe-9614-d28f3f3cc72d.mp4

**Comment by mifi** [comment]
ow that's very slow indeed. thanks for researching. I think we could file an issue at https://github.com/electron-userland/electron-builder to ask if it's possible to not extract every time the app starts up (e.g. whether that's a bug or a feature). However I'm not on windows so i cannot take the lead there.

**Comment by oliko-tk** [comment]
Yo creo que el zip anda  perfecto.. un agradecimiento sincero al desarrollador del progra.ma   muy util. 😀😁😁

**Comment by valueerrorx** [comment]
> ow that's very slow indeed. thanks for researching. I think we could file an issue at https://github.com/electron-userland/electron-builder to ask if it's possible to not extract every time the app starts up (e.g. whether that's a bug or a feature). However I'm not on windows so i cannot take the lead there.

that would be great because of this fact (that electron unpacks everytime even if you defined the tmp directory so it is the same everytime) new problems arise.. for example if you start the app a second time while the first one is still loading it will start to replace the files that are currently read by the first process...  => crash

**Pull request closed without merging**
