### PR TITLE
update translation(Chinese(Simplified))

### PR DESCRIPTION
**Pull request by chairc**
Add 4 new translations(Chinese(Simplified))

### CODE REVIEW

**Comment by mifi** [comment]
Could you please update here instead? https://hosted.weblate.org/projects/losslesscut/losslesscut/

**Comment by chairc** [comment]
I found that some Chinese words are not displayed in 3.39.0, but the translation is completed in this website.

**Comment by mifi** [comment]
Oh, then that's probably because I released 3.39.0 before the translation was fixed in weblate. So for the next release it will be included. I will pull this PR: https://github.com/mifi/lossless-cut/pull/842

**Comment by chairc** [comment]
I can also translate traditional Chinese

**Comment by mifi** [comment]
That's great! If you want to translate, you can go to weblate and conribute to the traditional Chinese translation there: https://hosted.weblate.org/projects/losslesscut/losslesscut/zh_Hant/
I'm sure many Chinese users will be happy if that translation is finished.

**Comment by mifi** [comment]
I have now pulled latest from weblate. there is now a merge conflict here. can you see if the changes from weblate are correct?

**Comment by chairc** [comment]
yep, it is correct.

**Comment by mifi** [comment]
Ok, thanks. I'll close this PR then. feel free to update strings in weblate if something is wrong

**Pull request closed without merging**
