### PR TITLE
Changes the default selection on Trash Dialog

### PR DESCRIPTION
**Pull request by Shakil-Shahadat**
Changed the default option to a safer one. See #541 point 2.

### CODE REVIEW

**Comment by mifi** [comment]
Thanks. However I'm not sure it's that dangerous to default to all files, because it is a trash after all, so it shouldn't permanently delete the files. And in versions prior to this, the user only had to press the trash icon, then enter to trash the source file, so I think people expect to be able to do that still

**Comment by Shakil-Shahadat** [comment]
Here is my reasoning for changing the default.
1. If there is no recycle bin, trash deletes the files permanently. See #537.
2. I have set up a test folder with some video files in it. After testing, I delete everything except the source file so that I can start afresh in the next test and I do this a lot. Changing the option every time is kind of annoying, failing to do so is even more annoying. Having a safer option means one less thing to worry. I don't have to delete the CSV file that much.
3. Even if the default changes, it just requires one click to select the desired option, not much inconvenient.

**Comment by mifi** [comment]
gotcha. I agree. in such case I think that default selected button should be trash instead of cancel

**Comment by mifi** [comment]
thx

**Pull request merged**
