### PR TITLE
Fix: Current selected format with size of current selected item.

### PR DESCRIPTION
**Pull request by wviana**
Hi there, got into this project after seeing the [T3 guy video.
](https://www.youtube.com/live/KPfet1IoH1Q?)
I was thinking about an app that would facilitate this "waterfall" (live -> video -> cuts) content creation flow.

This apps fits a lot on this, and maybe I will try to integrate some of the ideias I have in it.

But as a first contact with this project I notice that the format select was way bigger than necessary, it was keeping some empty space after the end of the selected format. So I tweaked around and could set this format select to be always the size of current selected format.

Hope you like it.

### CODE REVIEW

**Comment by mifi** [comment]
Hi. Thanks for your pr! What are the changes in topmenu for? And what is the purpose of the useState import?

**Comment by wviana** [comment]
Oh. Sorry. The useState was for a approach I was going to take before finding this one. Will remove it. 

The change is just a small fix to this format select. It was "wasting" some space or cutting it. This change always set the width of it matching the current selected item. 

You should be able to checkout this breach and checkout how it looks like, should always looks fine. 

English is not my first language, please feel free for asking for more clarification if needed.

**Comment by wviana** [comment]
Good morning, just removed the unused  `useState` and fixed the formatting for that that lint found out.

**Comment by mifi** [comment]
could you provide a screenshot showing the issue you're trying to fix?

for me on macos the format select is not way bigger than its content:
Screenshot 2023-04-18 at 09 43 48

> The change is just a small fix to this format select. It was "wasting" some space or cutting it. This change always set the width of it matching the current selected item.

I understand that your change to [OutputFormatSelect.jsx](https://github.com/mifi/lossless-cut/pull/1565/files#diff-c3a4ffea803b242a41e53b40814314ef9ff3413f3f91f8dbe5f45f85e8298f14) will do that, but i'm not sure how the changes to [TopMenu.jsx](https://github.com/mifi/lossless-cut/pull/1565/files#diff-bfc8b1e0008b9490988e7655d7801e3774bc316e8fe148d510343b1ad4e1589e) are related to that.

**Comment by wviana** [comment]
> for me on macos the format select is not way bigger than its content:

Yeap, it was shorter, as I told before, I was getting shorter than text.

>  It was "wasting" some space or cutting it.

By removing the hardcoded width of the component it started to use the width of the widest option from the selected. This is why I did that math to set format select according to current selected option width. Now it should be always responsive.

**Before**
Screenshot from 2023-04-18 14-20-00

**After**
Screenshot from 2023-04-18 14-21-31

**Comment by mifi** [comment]
seems there's some issue with your "after" UI:

Screenshot 2023-04-18 at 18 43 29

TBH I'm not sure if this is an improvement, because I don't think it's **that** interesting to see the whole format name at all times. you can always click the format select to get a dropdown and see the full names.

also still not sure about TopMenu changes

**Comment by wviana** [comment]
You're right, just notice it. Will take a better look at this when I get some time here.

About the changes in TopMenu, instead of having a empty div with flex 1 to fill all space between left and right items, I created on div for each side and set the top to space between, removing the need to that empty div to separate one side from the other.

**Comment by wviana** [comment]
Ok, just fiexed it. It was overlapping cause of a manual padding that was being set. 


Screenshot from 2023-04-18 15-14-32

**Comment by wviana** [comment]
> > About the changes in TopMenu, instead of having a empty div with flex 1 to fill all space between left and right items, I created on div for each side and set the top to space between, removing the need to that empty div to separate one side from the other.
> 
> what's the benefit of doing this?

Oh. This empty div with flex 1 is kind of a hack. Other than it, this way would allow to add items in this toolbar center. 

Do you have some other proposal for achieving this and behavior?

**Comment by mifi** [comment]
> Other than it, this way would allow to add items in this toolbar center.

Which items did you add to the toolbar center? it's not clear to me from looking at the screenshots

**Comment by wviana** [comment]
> > Other than it, this way would allow to add items in this toolbar center.
> 
> Which items did you add to the toolbar center? it's not clear to me from looking at the screenshots

Didn't add anything at the center. Was just answering your question, what would be the advantages. 

All that was done was setting the format width to auto the selected option width. Other than it was just some code cleaning to better usage of flexbox. 

Please checkout into this code and run it. Should be really easy to do as there wasn't any change in dependencies or any other.

**Comment by mifi** [comment]
ok, will have a look, thanks. i just want to make sure first that i understand what are the changes and why they were made, because when a lot of unrelated lines are changed, then it makes it harder for me to review what's actually affected/changed.

**Comment by mifi** [comment]
Looking at this again, I don't think we need to expand the format select button. As long as it shows the short name of the selected format, I tihkn it's ok. and with the current fixed size, it seems to do that nicely for all formats, even longer ones like matroska:

Screenshot 2023-09-24 at 13 33 35

if people are unsure, they can just click it to expand the full name. thanks anyways!

**Pull request closed without merging**
