### PR TITLE
Cleanup option in app state, bug fix.

### PR DESCRIPTION
**Pull request by Rubens10010**
Hi,
I noticed in latest release the cleanup dialog was closing the video preview even if action was canceled. (Fixed)
I also added a state variable cleanupOption to keep last user's picked option in cleanup dialog.
Finally I put default cleanup option to 'all' since is the one I use the most.
Maybe this changes can be merged... or do you have some observations?

### CODE REVIEW

**Comment by Shakil-Shahadat** [comment]
About changing the default cleanup option to 'all', see #581.

**Comment by mifi** [comment]
Closing even if dialog cancelled is how it always used to work, so I'm not sure if it's right to change it. I would think some people rely on that button (and the <kbd>d</kbd> shortcut) to close the file and optionally delete source. (the dialog used to say "do you want to delete source file?")

**Comment by Rubens10010** [comment]
@Shakil-Shahadat I understand a safer option is better but since this preferred option can be set in state after first use of trashing then I see no problem.
@mifi I think this is a bug because If I cancelled my action it means I want to go back to previous state. But currently my video is closed and I have to drag it back to continue working. In the solution I propose video is closed only if user has chosen any option and clicked on trash button.

**Comment by mifi** [comment]
Thanks for this PR, I solved this in a little bit different way, by just storing the state for the current session and using checkboxes:
Screenshot 2021-04-05 at 23 18 15

**Comment by mattack1** [comment]
Does this mean there isn't a way to save that pref permanently?  Having to answer it once per launch is a pain (esp since I personally edit one file, then quit).

**Comment by mifi** [comment]
> Does this mean there isn't a way to save that pref permanently? Having to answer it once per launch is a pain (esp since I personally edit one file, then quit).

is it that big of a problem? how often do you restart the app? I will make "trash auto-generated-files" default selected, so you have to click up to two checkboxes followed by a confirm button. could implement a permanent storage also, but then have to think about how to let the user reset this state if this dialog is permanently hidden.

**Pull request closed without merging**
