### PR TITLE
Tranlation to Spanish

### PR DESCRIPTION
**Pull request by egoitzro**
Hi, I make a fork of your project and translate to spanish, because I would like it to be in this language. Thanks

### CODE REVIEW

**Comment by mifi** [comment]
Hi. I just pulled translations from [weblate](https://hosted.weblate.org/projects/losslesscut/losslesscut)
Is it you who added translations on weblate as well? If not, then we need to find some way to merge your changes with the ones that came from weblate (which is the official way of translating LosslessCut)

**Comment by egoitzro** [comment]
> 
> 
> Hi. I just pulled translations from [weblate](https://hosted.weblate.org/projects/losslesscut/losslesscut)
> Is it you who added translations on weblate as well? If not, then we need to find some way to merge your changes with the ones that came from weblate (which is the official way of translating LosslessCut)

Hi,

As I did not know how to proceed when translating, I did it through both platforms, both through github and weblate

Thanks and best regards

**Comment by mifi** [comment]
Oh ok. So I think we can close this PR then, right? I already pulled the spanish from weblate

**Comment by egoitzro** [comment]
> 
> 
> Oh ok. So I think we can close this PR then, right? I already pulled the spanish from weblate

Yes, you can close the pr.

PS: I have seen that some translation string is missing and it is already 100% on the weblate.

Thanks

**Comment by mifi** [comment]
yes there are some menus etc that are not yet translateable,see #346

**Pull request closed without merging**
