### PR TITLE
Buildable on Windows 10

### PR DESCRIPTION
**Pull request by Effektgubben**
Using cross-env to make it build on other platforms. Only tested on Windows 10

### CODE REVIEW

**Comment by mifi** [comment]
tack så mycket!

could you remove the `.vs/` files from your pr and install cross-env using `yarn add -D cross-env` instead of npm? if not i can do it later

**Comment by Effektgubben** [comment]
Whoops, beklager
I'll fix it tomorrow unless you beat me to it

**Comment by Effektgubben** [comment]
That should be it :) Again I've only tested on Win10  so I can't guarantee anything. Thanks for supporting me even though I hardly know what I'm doing.

**Comment by mifi** [comment]
thanks again

**Pull request merged**
