### PR TITLE
Add bookmark support via hotkey; saves timestamps to accompanying txt

### PR DESCRIPTION
**Pull request by debuggeek**

### CODE REVIEW

**Comment by debuggeek** [comment]
Very quick an dirty to share idea at this point, but if interest then happy to clean up further if desired

**Comment by mifi** [comment]
Hi. What is the use case for this?

**Comment by debuggeek** [comment]
So my use case for adding this, was incremental to possible multi-cut.  I can have another person review video and mark time codes.  Then I hope to have a follow-on option that can auto-cut X seconds before and after each of those time codes

**Comment by debuggeek** [comment]
Also happy to keep in my fork till I have more of it done too, just wanted to share back if there was other interested

**Comment by mifi** [comment]
Ok cool, I'll leave this for a little to see if it's something many people want

**Comment by leejunseok** [comment]
I would love this feature. It would almost halve my storage requirements, since today I store both the original video and the dozens of clips I take from that original video.

**Comment by mifi** [comment]
Export/import timestamps from CSV is now implemented in newest version along with many other new features, i will close this

**Pull request closed without merging**
